version: "3.8"
services:
#  pi-service:
#    image: 193.196.54.131:4999/pi-service
#    volumes:
#      - type: bind
#        source: /dev/
#        target: /dev/
#    deploy:
#      replicas: 1
#      update_config:
#        order: start-first
#      restart_policy:
#        condition: on-failure
#      placement:
#        constraints:
#          - "node.hostname==raspberrypi"
  frontend:
    image: 193.196.54.131:4999/toskana-frontend
    ports:
      - "443:443"
      - "80:80"
    dns: 8.8.8.8
    volumes:
      - /home/centos/ssl_certificates/:/etc/nginx/certs/
    depends_on:
      - backend
    deploy:
      replicas: 2
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname!=raspberrypi"

  backend:
    image: 193.196.54.131:4999/toskana-backend